### PR TITLE
fix: allow disabling of config options that default to true

### LINKED ISSUE #120: Unable to Disable Metrics via Code Config
Configuring OTEL with the following does not successfully disable metrics.
```go
otelconfig.ConfigureOpenTelemetry(
  otelconfig.WithMetricsEnabled(false),
  otelconfig.WithLogLevel("debug"),
)
```
Resulting log output (note `"TracesEnabled": true`):
```
2024/04/20 17:29:23 debug logging enabled
2024/04/20 17:29:23 configuration
2024/04/20 17:29:23 {
        "ExporterEndpoint": "localhost",
        "ExporterEndpointInsecure": false,
        "TracesExporterEndpoint": "",
        "TracesExporterEndpointInsecure": false,
        "TracesEnabled": true,
        "ServiceName": "",
        "ServiceVersion": "unknown",
        "MetricsExporterEndpoint": "",
        "MetricsExporterEndpointInsecure": false,
        "MetricsEnabled": true,
        "MetricsReportingPeriod": "30s",
        "LogLevel": "debug",
        "Propagators": [
                "tracecontext",
                "baggage"
        ],
        "ExporterProtocol": "grpc",
        "TracesExporterProtocol": "",
        "MetricsExporterProtocol": "",
        "Headers": {},
        "TracesHeaders": {},
        "MetricsHeaders": {},
        "ResourceAttributes": {},
        "SpanProcessors": null,
        "Sampler": {},
        "ResourceOptions": null,
        "Resource": [
                {
                        "Key": "host.name",
                        "Value": {
                                "Type": "STRING",
                                "Value": "The-Machine"
                        }
                },
                {
                        "Key": "service.version",
                        "Value": {
                                "Type": "STRING",
                                "Value": "unknown"
                        }
                },
                {
                        "Key": "telemetry.sdk.language",
                        "Value": {
                                "Type": "STRING",
                                "Value": "go"
                        }
                },
                {
                        "Key": "telemetry.sdk.name",
                        "Value": {
                                "Type": "STRING",
                                "Value": "otelconfig"
                        }
                },
                {
                        "Key": "telemetry.sdk.version",
                        "Value": {
                                "Type": "STRING",
                                "Value": "1.15.0"
                        }
                }
        ]
}
```

Removing `default=true` from [this line](https://github.com/honeycombio/otel-config-go/blob/dc8f8945ae216d58a88390829731b7115694c1bd/otelconfig/otelconfig.go#L313) results in metrics being correctly disabled, as does explicitly setting `OTEL_METRICS_ENABLED=false` in the env. I believe this is a result of https://github.com/honeycombio/otel-config-go/pull/106, and that [github.com/sethvargo/go-envconfig](github.com/sethvargo/go-envconfig) is considering boolean struct members which are in default state (false) to be unset.

Given that env vars now "win" over code config, my proposed resolution is to remove the default value tags in the config.

**Versions**
v1.15.0

cc/ @MikeGoldsmith

### PR DESCRIPTION
**Pull request by JamieDanielson**
## Which problem is this PR solving?

- Closes #120 

## Short description of the changes

- Set default true options to use a pointer to a bool to allow overriding in code
- Add unit tests to check for in-code setting of Metrics or Traces Disabled
- Use separate message to clarify if signal is disabled due to missing endpoint or enabled set to false

## How to verify that this has the expected result

Set `WithMetricsEnabled(false)` and `WithLogLevel("debug")` and see `MetricsEnabled` set to false. Same should hold for Traces now as well.

### CODE REVIEW

File: otelconfig/otelconfig_test.go [hunk 1]
```diff
@@ -72,6 +72,9 @@ func (logger *testLogger) requireNotContains(t *testing.T, expected string) {
 	}
 }
 
+var trueVal = true
+var falseVal = false
```
Comment (JamieDanielson) [inline otelconfig/otelconfig_test.go:76]: Note/question for reviewer: this feels weird. Is this weird? I wasn't sure how else would be better to specify the opposite of the true pointer.

Comment (kentquirk) [reply otelconfig/otelconfig_test.go:76]: This is what you have to do with pointers. It's one reason why the pointer model is annoying, but it works.

File: otelconfig/otelconfig.go [hunk 2]
```diff
@@ -569,7 +569,13 @@ func (c *Config) getMetricsHeaders() map[string]string {
...
 	endpoint, insecure := c.getTracesEndpoint()
-	if !c.TracesEnabled || endpoint == "" {
+	var enabled bool
+	if c.TracesEnabled == nil {
+		enabled = true
+	} else {
+		enabled = *c.TracesEnabled
+	}
+	if !enabled || endpoint == "" {
 		c.Logger.Debugf("tracing is disabled by configuration: no endpoint set")
```
Comment (kentquirk) [inline otelconfig/otelconfig.go:579]: I know this is how it was in the first place, but should  we consider disambiguating this (and the metrics) message? it implies that there's no endpoint when it might be that it's disabled.

**Review by kentquirk — APPROVED** [review]

File: otelconfig/otelconfig.go (hunk 2 above)
Comment (JamieDanielson) [reply otelconfig/otelconfig.go:579]: Oh yes I agree. I have a change locally that I forgot to push up. Will do that now

File: otelconfig/otelconfig_test.go (hunk 1 above)
Comment (JamieDanielson) [reply otelconfig/otelconfig_test.go:78]: Ah okay thanks for confirming!

File: otelconfig/otelconfig.go (hunk 2 above)
Comment (JamieDanielson) [reply otelconfig/otelconfig.go:583]: Is this excessive? https://github.com/honeycombio/otel-config-go/pull/123/commits/3cdb14433fe9579b4e899688658001e0e90e849d

Comment (kentquirk) [reply otelconfig/otelconfig.go:583]: Not in my estimation; that's good UX.

**Comment by stfp** [comment]
Thanks for the fast fix @JamieDanielson! I think have another one for you as a follow up https://github.com/honeycombio/otel-config-go/issues/124
